echo Installing dependencies...
pip3 install tk

echo Installing dependencies...
pip install pyautogui

echo Installing CocoaTabs v0.1.1...
python install.py

echo Installing CocoaTabs v0.1.1...
rm windows_installer.bat